---
- name: Install basic packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ basic_packages }}"
  tags:
    - debug

- name: Install yq 
  shell: |
    wget https://github.com/mikefarah/yq/releases/download/{{VERSION}}/{{BINARY}} -O /usr/bin/yq &&\
    chmod +x /usr/bin/yq
  vars:
    VERSION: v4.2.0
    BINARY: yq_linux_amd64  
  args:
    chdir: /tmp


- name: Install Python 3.5 but do not select it
  alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/bin/python
    state: present
  
- name: Install the Docker Engine
  shell: |
    sudo apt-get update -y
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update -y
    sudo apt-get install -y  docker-ce docker-ce-cli containerd.io docker-compose-plugin

- name: Start and Enable Docker
  service:
      name: "docker"
      state: started
      enabled: yes

- name: "Install helm {{ packages.helm_version }} "
  shell: |
    wget https://get.helm.sh/helm-{{ packages.helm_version | default("v3.8.2") }}-linux-amd64.tar.gz
    tar -zxvf helm-{{ packages.helm_version | default("v3.8.2") }}-linux-amd64.tar.gz
    sudo mv linux-amd64/helm /usr/local/bin/helm
    rm helm-{{ packages.helm_version | default("v3.8.2") }}-linux-amd64.tar.gz
  args:
    chdir: /tmp/

- name: Install Kubectl {{ packages.kubectl_version }}
  shell: |
    curl -LO https://storage.googleapis.com/kubernetes-release/release/{{ packages.kubectl_version | default("v1.22.0") }}/bin/linux/amd64/kubectl
    chmod +x ./kubectl
    sudo mv ./kubectl /usr/local/bin/kubectl
  args:
    chdir: /tmp/

- name: Install the AWSCLI
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
    rm awscliv2.zip
  args:
    chdir: /tmp

- name: Enable Docker API
  shell: |
    sudo sed -e -i "/ExecStart/s|-H.*| -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock |" /lib/systemd/system/docker.service    
    sudo systemctl daemon-reload
    sudo systemctl restart docker
  args:
    executable: /bin/bash  
  when:
    - docker_slave is defined and docker_slave